[profile.default]
retries = { backoff = "exponential", count = 3, delay = "2s", jitter = true }
slow-timeout = { period = "120s", terminate-after = 4 }

# Define test groups here
[test-groups]
sequential-tests = { max-threads = 1, threads-required = 2 }

[[profile.default.overrides]]
filter = """
    test(=test_basic_concurrent) | 
    test(=resume_paused) | 
    test(=diverged_nonce) | 
    test(=pause_out_of_funds)
"""
test-group = "sequential-tests"