[profile.default]
retries = { backoff = "exponential", count = 3, delay = "2s", jitter = true }
slow-timeout = { period = "120s", terminate-after = 4 }
test-threads = 8  # Global default: 8 tests in parallel

[[profile.default.overrides]]
filter = """
    test(=test_basic_concurrent) | 
    test(=resume_paused) | 
    test(=diverged_nonce) | 
    test(=pause_out_of_funds)
"""
max-threads = 1
threads-required = 2
test-group = "sequential-tests"